[build]
command = "npx pnpm i --store=node_modules/.pnpm-store && npx pnpm build"
publish = "build"

[build.environment]
NPM_FLAGS = "--version"

[functions]
node_bundler = "esbuild"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://svelte-qwer.netlify.app/"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' https://svelte-qwer.netlify.app/  https://*.kwchang0831.dev https://giscus.app https://www.youtube.com"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "usb=()"

[[redirects]]
  from = "/partytown/plausible"
  to = "https://plausible.kwchang0831.dev/js/plausible.js"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
